gui:
  nerdFontsVersion: "3"
  splitDiff: "always"
  expandFocusedSidePanel: true
  # theme:
  #   # Border color of focused window
  #   activeBorderColor:
  #     - "#99ad6a" # green from nvim theme
  #     - bold
  #
  #   # Border color of non-focused windows
  #   inactiveBorderColor:
  #     - "#3a3a3a" # grey from nvim theme
  #
  #   # Border color of focused window when searching in that window
  #   searchingActiveBorderColor:
  #     - "#8fbfdc" # cyan from nvim theme
  #     - bold
  #
  #   # Color of keybindings help text in the bottom line
  #   optionsTextColor:
  #     - "#8197bf" # blue from nvim theme
  #
  #   # Background color of selected line.
  #   selectedLineBgColor:
  #     - "#8197bf" # blue from nvim theme
  #
  #   # Background color of selected line when view doesn't have focus.
  #   inactiveViewSelectedLineBgColor:
  #     - bold
  #
  #   # Foreground color of copied commit
  #   cherryPickedCommitFgColor:
  #     - "#8197bf" # blue from nvim theme
  #
  #   # Background color of copied commit
  #   cherryPickedCommitBgColor:
  #     - "#8fbfdc" # cyan from nvim theme
  #
  #   # Foreground color of marked base commit (for rebase)
  #   markedBaseCommitFgColor:
  #     - "#8197bf" # blue from nvim theme
  #
  #   # Background color of marked base commit (for rebase)
  #   markedBaseCommitBgColor:
  #     - "#fad07a" # yellow from nvim theme
  #
  #   # Color for file with unstaged changes
  #   unstagedChangesColor:
  #     - "#cf6a4c" # red from nvim theme
  #
  #   # Default text color
  #   defaultFgColor:
  #     - "#e8e8d3" # white from nvim theme
git:
# paging:
#   colorArg: always
#   pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
# edit: '[ -z "$NVIM_LISTEN_ADDRESS" ] && nvim -- "$FILENAME" || nvim --server "$NVIM_LISTEN_ADDRESS" --remote-send "<C-\\><C-n>:edit $FILENAME<CR>"'

# Custom keybindings
keybinding:
  files:
    # Ctrl+T: Open single file diff with nvim (default behavior)
    openDiffTool: '<c-t>'
    # Ctrl+Shift+T: Open ALL conflicted files in nvim tabs
    openMergeAll: '<c-T>'
customCommands:
  - key: '<c-T>'
    context: 'files'
    description: 'Open all merge conflicts in nvim tabs'
    command: '~/bin/nvim-merge-all'
    output: terminal
